version: "2.1"
services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    user: UID:GID # optional. Set custom user/group or uid/gid
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
    restart: unless-stopped

