name: docs
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout ntfy code
        uses: actions/checkout@v3
      -
        name: Checkout docs pages code
        uses: actions/checkout@v3
        with:
          repository: binwiederhier/ntfy-docs.github.io
          path: build/ntfy-docs.github.io
      -
        name: Build docs
        run: make docs
      -
        name: Copy generated docs
        run: rsync -av --delete docs/ build/ntfy-docs.github.io/docs/
      -
        name: Publish docs
        run: |
          cd build/ntfy-docs.github.io
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"          
          git add docs/
          git commit -m "Updated docs"
          git push origin main
