name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-pip
      - name: Install mkdocs
        run: sudo pip3 install mkdocs mkdocs-material mkdocs-minify-plugin
      - name: Build docs
        run: make docs
      - name: Run tests, formatting, vetting and linting
        run: make check
      - name: Run coverage
        run: make coverage
      # - name: Upload coverage to codecov.io
      #  run: make coverage-upload
